# Generated by Django 5.2.5 on 2025-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', '하'), ('medium', '중'), ('hard', '상')], default='medium', max_length=20),
        ),
    ]
